version: "3.8"

services:
  azuracast:
    image: azuracast/azuracast:latest
    container_name: azuracast_app
    restart: always
    # Altere as portas abaixo conforme disponibilidade
    ports:
      - "8052:80"         # Painel web acessível via http://IP:8052
      - "8453:443"        # HTTPS opcional (pode remover se usar proxy)
      - "18500-18550:8000-8050" # Portas das rádios (ajuste conforme necessidade)
    volumes:
      - azuracast_data:/var/azuracast
    environment:
      - AZURACAST_HTTP_PORT=80
      - AZURACAST_HTTPS_PORT=443
      - AUTO_ASSIGN_PORT_MIN=8000
      - AUTO_ASSIGN_PORT_MAX=8050
      - TZ=America/Sao_Paulo
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.azuracast.rule=Host(`radio.novasorocaba.net`)"
      - "traefik.http.routers.azuracast.entrypoints=https"
      - "traefik.http.routers.azuracast.tls.certresolver=letsencrypt"
      - "traefik.http.services.azuracast.loadbalancer.server.port=80"
      - "traefik.http.routers.azuracast-http.rule=Host(`radio.novasorocaba.net`)"
      - "traefik.http.routers.azuracast-http.entrypoints=http"
      - "traefik.http.routers.azuracast-http.middlewares=redirect-to-https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.middlewares.force-https.headers.customrequestheaders.X-Forwarded-Proto=https"
      - "traefik.http.routers.azuracast.middlewares=force-https"

volumes:
  azuracast_data:

networks:
  coolify:
    external: true
